# Generated by Django 4.0.4 on 2022-05-20 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('passwd', models.CharField(max_length=100)),
                ('confirmpasswd', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('insurance', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('dateOfBirth', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('zip', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productID', models.CharField(max_length=100)),
                ('productSKU', models.CharField(max_length=100)),
                ('productName', models.CharField(max_length=100)),
                ('productPrice', models.CharField(max_length=100)),
                ('productStock', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderAmount', models.CharField(max_length=100)),
                ('orderShipName', models.CharField(max_length=100)),
                ('orderShipAddress', models.CharField(max_length=300)),
                ('orderCity', models.CharField(max_length=100)),
                ('orderState', models.CharField(max_length=100)),
                ('orderZip', models.CharField(max_length=100)),
                ('orderPhone', models.CharField(max_length=100)),
                ('customer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplyorder.customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detailID', models.CharField(max_length=100)),
                ('detailName', models.CharField(max_length=100)),
                ('detailPrice', models.CharField(max_length=100)),
                ('detailSKU', models.CharField(max_length=100)),
                ('detailQuantity', models.CharField(max_length=100)),
                ('detailOrderID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplyorder.orders')),
                ('detailProductID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplyorder.products')),
            ],
        ),
    ]
