# Generated by Django 4.0.4 on 2022-05-25 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplyorder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='productID',
        ),
    ]
