# Generated by Django 4.0.4 on 2022-05-25 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplyorder', '0002_remove_products_productid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='productSKU',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
